export default [
  {
    id: 1,
    title: "meme-generator-app",
    badge1: "images/badges/React.png",
    badge2: "",
    badge3: "",
    badge4: "",
    description:
      "An app where the User can generate memes template with their desired text as well as desired position whether it is top or bottom.",
    link: "",
    status: false,
  },
  {
    id: 2,
    title: "AirBnb-Experiences-clone",
    badge1: "images/badges/React.png",
    badge2: "",
    badge3: "",
    badge4: "",
    description:
      "A clone of the ''AirBnB-Experiences'' aspect of the AirBnB application.",
    link: "https://github.com/Jean809/AirBnb-Experiences-clone",
    status: true,
  },
  {
    id: 3,
    title: "todo-app",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "An application that stores the daily ''to-do'' on a day by day basis of the user input. It allows the user to add and remove accordingly.",
    link: "https://github.com/Jean809/todo-app",
    status: false,
  },
  {
    id: 4,
    title: "Hangman-game",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "A guessing game where a player thinks of a word and tries guessing as the user/hangman approaches death.",
    link: "https://github.com/Jean809/Hangman-game",
    status: false,
  },
  {
    id: 5,
    title: "LendSpree-Website",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "This project consists of a financial lending website which was done purely for HTML/CSS practice purposes.",
    link: "https://github.com/Jean809/LendSpree-website",
    status: true,
  },
  {
    id: 6,
    title: "hotel-Website",
    badge1: "",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "This website consists of a hotel website. The purpose of this project was to demonstrate and practice my HTML/CSS skills outside of the JavaScript scope.",
    link: "https://github.com/Jean809/hotel-website",
    status: true,
  },
  {
    id: 7,
    title: "Bank-app",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "This is a bank application that allows the user to transfer x amount of funds between pre-recorded data. Each user has their own unique ''user'' and ''pin'' login information. ",
    link: "https://github.com/Jean809/Bank-App",
    status: true,
  },
  {
    id: 8,
    title: "Pig-Game",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "About This a 2-player game application that allows users to throw dices and record their data as they are playing. The player with the highest score wins the game.",
    link: "https://github.com/Jean809/Pig-Game",
    status: true,
  },
  {
    id: 9,
    title: "Guess-My-Number",
    badge1: "images/badges/JavaScript.png",
    badge2: "images/badges/HTML.png",
    badge3: "images/badges/CSS.png",
    badge4: "",
    description:
      "A game application where the user needs to guess the number. The user receives feedback hints as to how far they are before the correct number. ",
    link: "https://jean809.github.io/Guess-My-Number/",
    status: true,
  },
];
